// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview A WhatsApp booking confirmation AI agent.
 *
 * - sendWhatsAppBookingConfirmation - A function that sends WhatsApp booking confirmations.
 * - SendWhatsAppBookingConfirmationInput - The input type for the sendWhatsAppBookingConfirmation function.
 * - SendWhatsAppBookingConfirmationOutput - The return type for the sendWhatsAppBookingConfirmation function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SendWhatsAppBookingConfirmationInputSchema = z.object({
  customerName: z.string().describe('The name of the customer.'),
  salonName: z.string().describe('The name of the salon.'),
  appointmentDateTime: z.string().describe('The date and time of the appointment.'),
  serviceNames: z.array(z.string()).describe('The names of the services booked.'),
  staffName: z.string().describe('The name of the staff member assigned to the appointment.'),
  phoneNumber: z.string().describe('The customer phone number with country code.'),
});
export type SendWhatsAppBookingConfirmationInput = z.infer<typeof SendWhatsAppBookingConfirmationInputSchema>;

const SendWhatsAppBookingConfirmationOutputSchema = z.object({
  messageId: z.string().describe('The ID of the sent WhatsApp message.'),
});
export type SendWhatsAppBookingConfirmationOutput = z.infer<typeof SendWhatsAppBookingConfirmationOutputSchema>;

export async function sendWhatsAppBookingConfirmation(input: SendWhatsAppBookingConfirmationInput): Promise<SendWhatsAppBookingConfirmationOutput> {
  return sendWhatsAppBookingConfirmationFlow(input);
}

const sendWhatsAppMessage = ai.defineTool(
  {
    name: 'sendWhatsAppMessage',
    description: 'Sends a WhatsApp message to a customer using the WhatsApp Cloud API.',
    inputSchema: z.object({
      phoneNumber: z.string().describe('The customer phone number with country code.'),
      message: z.string().describe('The content of the WhatsApp message.'),
    }),
    outputSchema: z.object({
      messageId: z.string().describe('The ID of the sent WhatsApp message.'),
    }),
  },
  async (input) => {
    // TODO: Implement the actual WhatsApp message sending logic here.
    // This is a placeholder implementation.
    console.log(`Sending WhatsApp message to ${input.phoneNumber}: ${input.message}`);
    const messageId = Math.random().toString(36).substring(7); // Placeholder message ID.
    return { messageId };
  }
);

const prompt = ai.definePrompt({
  name: 'whatsAppBookingConfirmationPrompt',
  tools: [sendWhatsAppMessage],
  input: {schema: SendWhatsAppBookingConfirmationInputSchema},
  output: {schema: SendWhatsAppBookingConfirmationOutputSchema},
  prompt: `You are a helpful assistant that sends WhatsApp booking confirmations to customers.

  Use the sendWhatsAppMessage tool to send the confirmation message.

  The salon name is: {{{salonName}}}
  The customer name is: {{{customerName}}}
  The appointment date and time is: {{{appointmentDateTime}}}
  The services booked are: {{#each serviceNames}}{{{this}}}{{#unless @last}}, {{/unless}}{{/each}}
  The staff member assigned is: {{{staffName}}}
  The customer's phone number is: {{{phoneNumber}}}

  Generate a personalized and friendly WhatsApp message confirming the booking details.  The message should include the salon name, customer name, appointment date and time, services booked, and assigned staff member.  If the appointment is in less than 24 hours, remind the customer to come. Add a pleasant salutation and closing.
`,
});

const sendWhatsAppBookingConfirmationFlow = ai.defineFlow(
  {
    name: 'sendWhatsAppBookingConfirmationFlow',
    inputSchema: SendWhatsAppBookingConfirmationInputSchema,
    outputSchema: SendWhatsAppBookingConfirmationOutputSchema,
  },
  async input => {
    const {customerName, salonName, appointmentDateTime, serviceNames, staffName, phoneNumber} = input;

    const promptResult = await prompt(input);
    return promptResult.output!;
  }
);
